### ISSUE TITLE
tensorflow

### ISSUE THREAD

**Issue by prayagupa** [upd-machine/ml-coursera#1]
just a note
-----------

```bash
sudo easy_install --upgrade pip
Searching for pip
Reading https://pypi.python.org/simple/pip/
Download error on https://pypi.python.org/simple/pip/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
Couldn't find index page for 'pip' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
No local packages or download links found for pip
error: Could not find suitable distribution for Requirement.parse('pip')

```

using pip3
-----------

```
pip3 install tensorflow 
Requirement already satisfied: tensorflow in /usr/local/lib/python3.6/site-packages (1.7.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/site-packages (from tensorflow) (1.11.0)
Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.6/site-packages (from tensorflow) (0.29.0)
Requirement already satisfied: absl-py>=0.1.6 in /usr/local/lib/python3.6/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.6/site-packages (from tensorflow) (1.13.3)
Requirement already satisfied: grpcio>=1.8.6 in /usr/local/lib/python3.6/site-packages (from tensorflow) (1.11.0)
Requirement already satisfied: protobuf>=3.4.0 in /usr/local/lib/python3.6/site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.6/site-packages (from tensorflow) (1.1.0)
Requirement already satisfied: astor>=0.6.0 in /usr/local/lib/python3.6/site-packages (from tensorflow) (0.6.2)
Requirement already satisfied: tensorboard<1.8.0,>=1.7.0 in /usr/local/lib/python3.6/site-packages (from tensorflow) (1.7.0)
Requirement already satisfied: gast>=0.2.0 in /usr/local/lib/python3.6/site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from protobuf>=3.4.0->tensorflow) (32.2.0)
Requirement already satisfied: werkzeug>=0.11.10 in /usr/local/lib/python3.6/site-packages (from tensorboard<1.8.0,>=1.7.0->tensorflow) (0.14.1)
Requirement already satisfied: html5lib==0.9999999 in /usr/local/lib/python3.6/site-packages (from tensorboard<1.8.0,>=1.7.0->tensorflow) (0.9999999)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.6/site-packages (from tensorboard<1.8.0,>=1.7.0->tensorflow) (2.6.11)
Requirement already satisfied: bleach==1.5.0 in /usr/local/lib/python3.6/site-packages (from tensorboard<1.8.0,>=1.7.0->tensorflow) (1.5.0)
grpcio 1.11.0 has requirement protobuf>=3.5.0.post1, but you'll have protobuf 3.4.0 which is incompatible.

#un-install
pip3 uninstall tensorflow 
Uninstalling tensorflow-1.13.1:
  Would remove:
    /usr/local/bin/freeze_graph
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.7/site-packages/tensorflow-1.13.1.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-1.13.1
```

TensorFlow Linear Model - https://www.tensorflow.org/tutorials/wide

```
git clone https://github.com/tensorflow/models.git
cd models/official/wide_deep
python data_download.py
Traceback (most recent call last):
  File "data_download.py", line 26, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
```

I got `tensorboard --helpfull` somehow.

https://www.tensorflow.org/programmers_guide/summaries_and_tensorboard

```
$ tensorboard --logdir chatbot
2018-07-01 11:17:50.080369: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
TensorBoard 1.7.0 at http://MACC02V82BPHTD7:6006 (Press CTRL+C to quit)
```

which means can access board at http://localhost:6006/

**Comment by prayagupa** [comment]
pip3 install ipython
get https://repo.anaconda.com/archive/Anaconda3-5.2.0-MacOSX-x86_64.pkg

```
$ ipython notebook
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-112>", line 2, in initialize
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 308, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/application.py", line 450, in initialize
    self.parse_command_line(argv)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 303, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traitlets/config/application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/application.py", line 243, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/traitlets/config/application.py", line 445, in initialize_subcommand
    subapp = import_item(subapp)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'notebook'
```

**Comment by prayagupa** [comment]
solution

using virtualenv
-----------------

```
$ pip3 install --upgrade virtualenv 
Collecting virtualenv
  Downloading https://files.pythonhosted.org/packages/b6/30/96a02b2287098b23b875bc8c2f58071c35d2efe84f747b64d523721dc2b5/virtualenv-16.0.0-py2.py3-none-any.whl (1.9MB)
    100% |████████████████████████████████| 1.9MB 2.1MB/s 
grpcio 1.11.0 has requirement protobuf>=3.5.0.post1, but you'll have protobuf 3.4.0 which is incompatible.
Installing collected packages: virtualenv
Successfully installed virtualenv-16.0.0

$ virtualenv --system-site-packages -p python3 /Users/a1353612/py-env
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/a1353612/py-env/bin/python3
Also creating executable in /Users/a1353612/py-env/bin/python
Installing setuptools, pip, wheel...done.

cd /Users/a1353612/py-env/
source ./bin/activate

pip3 install --upgrade tensorflow

python3 hello-matrix-flow.py
```


verify
------

```
$ pip3 show tensorflow
Name: tensorflow
Version: 1.9.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.6/site-packages
Requires: setuptools, six, absl-py, tensorboard, termcolor, grpcio, gast, astor, wheel, protobuf, numpy
Required-by: 


$ ll /usr/local/lib/python3.6/site-packages/tensorflow
total 24864
-rw-r--r--   1 a1353612  admin     26182 Jul 24 22:45 __init__.py
drwxr-xr-x   3 a1353612  admin       102 Jul 24 22:46 __pycache__
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 app
drwxr-xr-x   3 a1353612  admin       102 Jul 24 22:46 aux-bin
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 bitwise
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 compat
drwxr-xr-x  95 a1353612  admin      3230 Jul 24 22:46 contrib
drwxr-xr-x  13 a1353612  admin       442 Jul 24 22:46 core
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 data
drwxr-xr-x   5 a1353612  admin       170 Jul 24 22:46 distributions
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 errors
drwxr-xr-x   6 a1353612  admin       204 Jul 24 22:46 estimator
drwxr-xr-x   5 a1353612  admin       170 Jul 24 22:46 examples
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 feature_column
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 gfile
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 graph_util
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 image
drwxr-xr-x   8 a1353612  admin       272 Jul 24 22:46 include
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 initializers
drwxr-xr-x  21 a1353612  admin       714 Jul 24 22:46 keras
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 layers
-rwxr-xr-x   1 a1353612  admin  12699108 Jul 24 22:45 libtensorflow_framework.so
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 linalg
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 logging
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 losses
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 manip
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 math
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 metrics
drwxr-xr-x   5 a1353612  admin       170 Jul 24 22:46 nn
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 profiler
drwxr-xr-x  27 a1353612  admin       918 Jul 24 22:46 python
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 python_io
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 resource_loader
drwxr-xr-x  12 a1353612  admin       408 Jul 24 22:46 saved_model
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 sets
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 sparse
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 spectral
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 strings
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 summary
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 sysconfig
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 test
drwxr-xr-x   7 a1353612  admin       238 Jul 24 22:46 tools
drwxr-xr-x   5 a1353612  admin       170 Jul 24 22:46 train
drwxr-xr-x   4 a1353612  admin       136 Jul 24 22:46 user_ops
```
